function [psi, term_scale] = Estimate_EM_ELBO_enhance(Input, obj, m_z_plus, v_z_plus)
  In = Input.In;
  Out = Input.Out;
  quan_step = Out.quan_step;
  y = obj.y;
  p = Out.p;
  MAX_TERM = Out.MAX_TERM;
  M = Input.M * Input.N;
  nuw = Input.nuw;

  y_vector  = Real_Matrix(y);
  y_real    = y_vector(1 : M);
  y_imag    = y_vector(M + 1 : 2 * M);

  q     = Out.q;

  q_up  = y_vector + quan_step / 2;
  q_low = y_vector - quan_step / 2;

  [pos1, ~] = find(y_vector == max(p));
  [pos2, ~] = find(y_vector == min(p));

  q_up(pos1)  = MAX_TERM;
  q_low(pos2) = -MAX_TERM;

  q_real_up = q_up(1 : M);
  q_imag_up = q_up(M + 1 : 2 * M);

  q_real_low = q_low(1 : M);
  q_imag_low = q_low(M + 1 : 2 * M);

  m_z_plus_vector = Real_Matrix(m_z_plus);
  m_real_z_plus = m_z_plus_vector(1 : M);
  m_imag_z_plus = m_z_plus_vector(M + 1 : 2 * M);

  v_z_plus_vector = [v_z_plus/2; v_z_plus/2];
  v_real_z_plus = v_z_plus_vector(1 : M);
  v_imag_z_plus = v_z_plus_vector(M + 1 : 2 * M);

  x0 = 0.1;

  options = optimoptions('fsolve','Display','none');

%%%%%%%%%%%%%%%%%%%%%%%%

  var_rho = @(psii) max(1e-7, psii ./ 2 + v_z_plus ./ 2);

  beta_real_low = @(psii) ...
    ( ...
      q_real_low - m_real_z_plus ...
    ) ...
    ./ ...
    ( ...
      sqrt( var_rho(psii) ) ...
    );

  beta_real_up = @(psii) ...
    ( ...
      q_real_up - m_real_z_plus ...
    ) ...
    ./ ...
    ( ...
      sqrt( var_rho(psii) ) ...
    );

  beta_imag_low = @(psii) ...
    ( ...
      q_imag_low - m_imag_z_plus ...
    ) ...
    ./ ...
    ( ...
      sqrt( var_rho(psii) ) ...
    );

  beta_imag_up = @(psii) ...
    ( ...
      q_imag_up - m_imag_z_plus ...
    ) ...
    ./ ...
    ( ...
      sqrt( var_rho(psii) ) ...
    );

  C_real = @(psii) ...
    ( ...
      normcdf( beta_real_up(psii) ) ...
      - ...
      normcdf( beta_real_low(psii) ) ...
    );

  C_imag = @(psii) ...
    ( ...
      normcdf( beta_imag_up(psii) ) ...
      - ...
      normcdf( beta_imag_low(psii) ) ...
    );

  virtual_mean_posterior      = @(psii) Out.Estimation_mean(y, psii, m_z_plus, v_z_plus);
  virtual_variance_posterior  = @(psii) Out.Estimation_variance(y, psii, m_z_plus, v_z_plus);

  hat_m_real_z = @(psii) real( virtual_mean_posterior( max(psii, 1e-7) ) );
  hat_m_imag_z = @(psii) imag( virtual_mean_posterior( max(psii, 1e-7) ) );

  hat_v_real_z = @(psii) virtual_variance_posterior( max(psii, 1e-7) ) / 2;
  hat_v_imag_z = @(psii) virtual_variance_posterior( max(psii, 1e-7) ) / 2;

  partial_C_real_partial_m = @(psii) ...
    ( ...
      C_real(psii) ...
      .* ...
      ( ...
        hat_m_real_z(psii) - m_real_z_plus ...
      ) ...
      ./ ...
      v_real_z_plus ...
    );

  partial_C_imag_partial_m = @(psii) ...
    ( ...
      C_imag(psii) ...
      .* ...
      ( ...
        hat_m_imag_z(psii) - m_imag_z_plus ...
      ) ...
      ./ ...
      v_imag_z_plus ...
    );

  partial_double_C_real_partial_double_m = @(psii) ...
    ( ...
      C_real(psii) ...
      .* ...
      ( ...
        hat_v_real_z(psii) - v_real_z_plus + ( hat_m_real_z(psii) - m_real_z_plus ).^2 ...
      ) ...
      ./ ...
      v_real_z_plus.^2 ...
    );

  partial_double_C_imag_partial_double_m = @(psii) ...
    ( ...
      C_imag(psii) ...
      .* ...
      ( ...
        hat_v_imag_z(psii) - v_imag_z_plus + ( hat_m_imag_z(psii) - m_imag_z_plus ).^2 ...
      ) ...
      ./ ...
      v_imag_z_plus.^2 ...
    );

  C_real_prime = @(psii) ...
    ( ...
      ( ...
        beta_real_low(psii) .* normpdf( beta_real_low(psii) ) ...
        - ...
        beta_real_up(psii)  .* normpdf( beta_real_up(psii) ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii) ...
      ) ...
    );

  C_imag_prime = @(psii) ...
    ( ...
      ( ...
        beta_imag_low(psii) .* normpdf( beta_imag_low(psii) ) ...
        - ...
        beta_imag_up(psii)  .* normpdf( beta_imag_up(psii) ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii) ...
      ) ...
    );

  partial_C_real_prime_partial_m = @(psii) ...
    ( ...
      ( ...
        normpdf( beta_real_low(psii) ) .* ( - 1 + beta_real_low(psii).^2 ) ...
        - ...
        normpdf( beta_real_up(psii) )  .* ( - 1 + beta_real_up(psii).^2 ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii).^(3/2) ...
      ) ...
    );

  partial_C_imag_prime_partial_m = @(psii) ...
    ( ...
      ( ...
        normpdf( beta_imag_low(psii) ) .* ( - 1 + beta_imag_low(psii).^2 ) ...
        - ...
        normpdf( beta_imag_up(psii) )  .* ( - 1 + beta_imag_up(psii).^2 ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii).^(3/2) ...
      ) ...
    );

  partial_double_C_real_prime_partial_double_m = @(psii) ...
    ( ...
      ( ...
        beta_real_low(psii) .* normpdf( beta_real_low(psii) ) ...
        .* ...
        ( ...
          - 1 ./ var_rho(psii) ...
          + ...
          ( ...
            beta_real_low(psii).^2 - 2 ...
          ) ...
          ./ ...
          sqrt( var_rho(psii) ) ...
        ) ...
        - ...
        beta_real_up(psii)  .* normpdf( beta_real_up(psii) )  ...
        .* ...
        ( ...
          - 1 ./ var_rho(psii) ...
          + ...
          ( ...
            beta_real_up(psii).^2  - 2 ...
          ) ...
          ./ ...
          sqrt( var_rho(psii) ) ...
        ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii) ...
      ) ...
    );

  partial_double_C_imag_prime_partial_double_m = @(psii) ...
    ( ...
      ( ...
        beta_imag_low(psii) .* normpdf( beta_imag_low(psii) ) ...
        .* ...
        ( ...
          - 1 ./ var_rho(psii) ...
          + ...
          ( ...
            beta_imag_low(psii).^2 - 2 ...
          ) ...
          ./ ...
          sqrt( var_rho(psii) ) ...
        ) ...
        - ...
        beta_imag_up(psii)  .* normpdf( beta_imag_up(psii) )  ...
        .* ...
        ( ...
          - 1 ./ var_rho(psii) ...
          + ...
          ( ...
            beta_imag_up(psii).^2  - 2 ...
          ) ...
          ./ ...
          sqrt( var_rho(psii) ) ...
        ) ...
      ) ...
      ./ ...
      ( ...
        4 .* var_rho(psii) ...
      ) ...
    );

%%%%%%%%%%%%%%%%%%%%%%%%

  partial_log_C_partial_psi = @(psii) ...
    ( ...
      C_real_prime(psii) ./ C_real(psii) ...
      + ...
      C_imag_prime(psii) ./ C_imag(psii) ...
    );

  partial_polynomial_partial_psi_A = @(psii) ...
    ( ...
      v_real_z_plus ...
      .* ...
      C_real_prime(psii) ...
      .* ...
      partial_double_C_real_partial_double_m(psii) ...
      ./ ...
      ( ...
        2 ...
        .* ...
        C_real(psii).^2 ...
      ) ...
      + ...
      v_imag_z_plus ...
      .* ...
      C_imag_prime(psii) ...
      .* ...
      partial_double_C_imag_partial_double_m(psii) ...
      ./ ...
      ( ...
        2 ...
        .* ...
        C_imag(psii).^2 ...
      ) ...
    );

  partial_polynomial_partial_psi_B = @(psii) ...
    ( ...
      v_real_z_plus ...
      .* ...
      partial_double_C_real_prime_partial_double_m(psii) ...
      ./ ...
      ( ...
        2 ...
        .* ...
        C_real(psii) ...
      ) ...
      + ...
      v_imag_z_plus ...
      .* ...
      partial_double_C_imag_prime_partial_double_m(psii) ...
      ./ ...
      ( ...
        2 ...
        .* ...
        C_imag(psii) ...
      ) ...
    );

  partial_polynomial_partial_psi = @(psii) ...
    ( ...
      - ...
      partial_polynomial_partial_psi_A(psii) ...
      + ...
      partial_polynomial_partial_psi_B(psii) ...
    );

  partial_hat_v_partial_psi_A = @(psii) ...
    ( ...
      2 ...
      .* ...
      v_real_z_plus.^2 ...
      .* ...
      partial_C_real_partial_m(psii).^2 ...
      .* ...
      C_real_prime(psii) ...
      ./ ...
      C_real(psii).^3 ...
      + ...
      2 ...
      .* ...
      v_imag_z_plus.^2 ...
      .* ...
      partial_C_imag_partial_m(psii).^2 ...
      .* ...
      C_imag_prime(psii) ...
      ./ ...
      C_imag(psii).^3 ...
    );

  partial_hat_v_partial_psi_B = @(psii) ...
    ( ...
      2 ...
      .* ...
      v_real_z_plus.^2 ...
      .* ...
      partial_C_real_partial_m(psii) ...
      .* ...
      partial_C_real_prime_partial_m(psii) ...
      ./ ...
      C_real(psii).^2 ...
      + ...
      2 ...
      .* ...
      v_imag_z_plus.^2 ...
      .* ...
      partial_C_imag_partial_m(psii) ...
      .* ...
      partial_C_imag_prime_partial_m(psii) ...
      ./ ...
      C_imag(psii).^2 ...
    );

  partial_hat_v_partial_psi_C = @(psii) ...
    ( ...
      v_real_z_plus.^2 ...
      .* ...
      partial_double_C_real_partial_double_m(psii) ...
      .* ...
      C_real_prime(psii) ...
      ./ ...
      C_real(psii).^2 ...
      + ...
      v_imag_z_plus.^2 ...
      .* ...
      partial_double_C_imag_partial_double_m(psii) ...
      .* ...
      C_imag_prime(psii) ...
      ./ ...
      C_imag(psii).^2 ...
    );

  partial_hat_v_partial_psi_D = @(psii) ...
    ( ...
      v_real_z_plus.^2 ...
      .* ...
      partial_double_C_real_prime_partial_double_m(psii) ...
      ./ ...
      C_real(psii) ...
      + ...
      v_imag_z_plus.^2 ...
      .* ...
      partial_double_C_imag_prime_partial_double_m(psii) ...
      ./ ...
      C_imag(psii) ...
    );

  partial_log_hat_v_partial_psi = @(psii) ...
    ( ...
      ( ...
          partial_hat_v_partial_psi_A(psii) ...
          - ...
          partial_hat_v_partial_psi_B(psii) ...
          - ...
          partial_hat_v_partial_psi_C(psii) ...
          + ... 
          partial_hat_v_partial_psi_D(psii) ...
      ) ...
      ./ ...
      ( ...
        2 .* hat_v_real_z(psii) ...
      ) ...
    );

  fun = @(psii) ...
    ( ...
      var_rho(psii) .* partial_log_C_partial_psi(psii) ...
      + ...
      var_rho(psii) .* partial_polynomial_partial_psi(psii) ...
      - ...
      var_rho(psii) .* partial_log_hat_v_partial_psi(psii) ...
    );

  funfun = @(psii) sum(fun(psii));

  psi = fsolve(funfun, x0, options);

  term_scale = ...
  abs( ...
    sum( ...
      ( ...
        hat_v_real_z(nuw) + hat_v_imag_z(nuw) + abs( hat_m_real_z(nuw) - m_real_z_plus ).^2 + abs( hat_m_imag_z(nuw) - m_imag_z_plus ).^2 ...
      ) ...
      ./ ...
      v_z_plus ...
      - 1 ...
      + log( v_z_plus ) ...
      - log( hat_v_real_z(nuw) + hat_v_imag_z(nuw) ) ...
    ) ...
  ) ...
  ./ ...
  abs( ...
    sum( ...
      log( C_real(nuw) ) + log( C_imag(nuw) ) ...
    ) ...
  );

end